# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Sebesta
email: chris.sebesta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chris Sebesta is an electrical engineer currently working on some personal programming projects
   in Java, SQL, XML, and C while also expanding basic knowledge in front end design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chrissebesta.com" # the base hostname & protocol for your site
twitter_username: zebesta
github_username:  zebesta
facebook_username: zebesta
linkedin_username: chrissebesta
instagram_username: zebesta

# Build settings
markdown: kramdown
